;cartridge mapper
EXPORT DEF MBC_RAM_ENABLE EQU 0x0000
EXPORT DEF MBC_ROM_BANK EQU 0x2000
EXPORT DEF MBC_ROM_BANK_HI EQU 0x3000
EXPORT DEF MBC_RAM_BANK EQU 0x4000

;joypad register
EXPORT DEF IO_JOYPAD EQU 0xFF00
EXPORT DEF JOYPAD_A EQU 0x01
EXPORT DEF JOYPAD_B EQU 0x02
EXPORT DEF JOYPAD_SEL EQU 0x04
EXPORT DEF JOYPAD_STR EQU 0x08
EXPORT DEF JOYPAD_R EQU 0x01
EXPORT DEF JOYPAD_L EQU 0x02
EXPORT DEF JOYPAD_U EQU 0x04
EXPORT DEF JOYPAD_D EQU 0x08
EXPORT DEF JOYPAD_SEL_DPAD EQU 0x20
EXPORT DEF JOYPAD_SEL_FACE EQU 0x10
EXPORT DEF JOYPAD_SEL_NONE EQU 0x30

;serial registers
EXPORT DEF IO_SERIAL_DATA EQU 0xFF01
EXPORT DEF IO_SERIAL_CTRL EQU 0xFF02
EXPORT DEF SERIAL_CLOCK EQU 0x01
EXPORT DEF SERIAL_SPEED EQU 0x02
EXPORT DEF SERIAL_TRIGGER EQU 0x80

;timer registers
EXPORT DEF IO_TIMER_HW EQU 0xFF04
EXPORT DEF IO_TIMER_SW EQU 0xFF05
EXPORT DEF IO_TIMER_LEN EQU 0xFF06
EXPORT DEF IO_TIMER_CTRL EQU 0xFF07
EXPORT DEF TIMER_SPEED EQU 0x03
EXPORT DEF TIMER_ENABLE EQU 0x04

;interrupt registers
EXPORT DEF IO_INTERRUPT_ENABLE EQU 0xFFFF
EXPORT DEF IO_INTERRUPT_REQUEST EQU 0xFF0F
EXPORT DEF INTERRUPT_VBLANK EQU 0x01
EXPORT DEF INTERRUPT_LCD EQU 0x02
EXPORT DEF INTERRUPT_TIMER EQU 0x04
EXPORT DEF INTERRUPT_SERIAL EQU 0x08
EXPORT DEF INTERRUPT_JOYPAD EQU 0x10

;audio registers
EXPORT DEF IO_SOUND1_SWEEP EQU 0xFF10
EXPORT DEF SWEEP_AMT EQU 0x07
EXPORT DEF SWEEP_DIRECTION EQU 0x08
EXPORT DEF SWEEP_SPEED EQU 0x70

EXPORT DEF IO_SOUND1_DUTY EQU 0xFF11
EXPORT DEF SOUND_LENGTH EQU 0x3F
EXPORT DEF SOUND_DUTY EQU 0xC0

EXPORT DEF IO_SOUND1_VOL EQU 0XFF12
EXPORT DEF ENV_SPEED EQU 0x07
EXPORT DEF ENV_DIRECTION EQU 0x08
EXPORT DEF ENV_VOLUME EQU 0xF0

EXPORT DEF IO_SOUND1_PITCHL EQU 0xFF13
EXPORT DEF IO_SOUND1_PITCHH EQU 0xFF14
EXPORT DEF PITCH_HIGH EQU 0x07
EXPORT DEF PITCH_LENGTH_ENABLE EQU 0x40
EXPORT DEF PITCH_TRIGGER_SOUND EQU 0x80

EXPORT DEF IO_SOUND2_SWEEP EQU 0xFF15
EXPORT DEF IO_SOUND2_DUTY EQU 0xFF16
EXPORT DEF IO_SOUND2_VOL EQU 0xFF17
EXPORT DEF IO_SOUND2_PITCHL EQU 0xFF18
EXPORT DEF IO_SOUND2_PITCHH EQU 0xFF19

EXPORT DEF IO_SOUND3_SWEEP EQU 0xFF1A
EXPORT DEF WAVE_DAC_ENABLE EQU 0x80

EXPORT DEF IO_SOUND3_DUTY EQU 0xFF1B
EXPORT DEF IO_SOUND3_VOL EQU 0xFF1C
EXPORT DEF WAVE_VOLUME EQU 0x60

EXPORT DEF IO_SOUND3_PITCHL EQU 0xFF1D
EXPORT DEF IO_SOUND3_PITCHH EQU 0xFF1E

EXPORT DEF IO_SOUND4_SWEEP EQU 0xFF1F
EXPORT DEF IO_SOUND4_DUTY EQU 0xFF20
EXPORT DEF IO_SOUND4_VOL EQU 0xFF21
EXPORT DEF IO_SOUND4_PITCHL EQU 0xFF22
EXPORT DEF NOISE_MULT EQU 0x07
EXPORT DEF NOISE_METALLIC EQU 0x08
EXPORT DEF NOISE_PITCH EQU 0xF0

EXPORT DEF IO_SOUND4_PITCHH EQU 0xFF23

EXPORT DEF IO_SOUND_MAIN_VOLUME EQU 0xFF24
EXPORT DEF IO_SOUND_MAIN_PAN EQU 0xFF25
EXPORT DEF IO_SOUND_MAIN_CTRL EQU 0xFF26
EXPORT DEF SPEAKERS_ENABLE EQU 0x80

;wave RAM
EXPORT DEF IO_WAVERAM EQU 0xFF30

;LCD registers
EXPORT DEF IO_LCD_CTRL EQU 0xFF40
EXPORT DEF SPRITE_PRIORITY EQU 0x01
EXPORT DEF SPRITE_ENABLE EQU 0x02
EXPORT DEF SPRITE_SIZE EQU 0x04
EXPORT DEF BKG_MAP_SELECT EQU 0x08
EXPORT DEF BKG_TILE_BANK EQU 0x10
EXPORT DEF WIN_ENABLE EQU 0x20
EXPORT DEF WIN_MAP_SELECT EQU 0x40
EXPORT DEF LCD_ENABLE EQU 0x80

EXPORT DEF IO_LCD_STATUS EQU 0xFF41
EXPORT DEF PPU_MODE EQU 0x03
EXPORT DEF LCD_Y_COMPARE EQU 0x04
EXPORT DEF STAT_IRQ_HBLANK EQU 0x08
EXPORT DEF STAT_IRQ_VBLANK EQU 0x10
EXPORT DEF STAT_IRQ_OAMSCAN EQU 0x20
EXPORT DEF STAT_IRQ_LYC EQU 0x40

EXPORT DEF IO_SCROLL_Y EQU 0xFF42
EXPORT DEF IO_SCROLL_X EQU 0xFF43
EXPORT DEF IO_LCD_CURRENT_LINE EQU 0xFF44
EXPORT DEF IO_LCD_Y_COMPARE EQU 0xFF45
EXPORT DEF IO_OAM_DMA EQU 0xFF46
EXPORT DEF IO_DMG_BKG_PALETTE EQU 0xFF47
EXPORT DEF IO_DMG_OBJ_PALETTE1 EQU 0xFF48
EXPORT DEF IO_DMG_OBJ_PALETTE2 EQU 0xFF49

EXPORT DEF IO_WINDOW_Y EQU 0xFF4A
EXPORT DEF IO_WINDOW_X EQU 0xFF4B

;GBC registers
EXPORT DEF IO_DOUBLESPEED EQU 0xFF4D
EXPORT DEF IO_VRAM_BANK EQU 0xFF4F
EXPORT DEF IO_DMA_SRC_H EQU 0xFF51
EXPORT DEF IO_DMA_SRC_L EQU 0xFF52
EXPORT DEF IO_DMA_DST_H EQU 0xFF53
EXPORT DEF IO_DMA_DST_L EQU 0xFF54
EXPORT DEF IO_DMA_TRIGGER EQU 0xFF55
EXPORT DEF GDMA_NUM_TILES EQU 0x7F
EXPORT DEF GDMA_HBLANK EQU 0x80

EXPORT DEF IO_INFRARED_PORT EQU 0xFF56
EXPORT DEF IR_EMIT_ACTIVE EQU 0x01
EXPORT DEF IR_LIGHT_LEVEL EQU 0x02
EXPORT DEF IR_READ_ENABLE EQU 0xC0

;color RAM
EXPORT DEF IO_CRAM_BKG_SELECT EQU 0xFF68
EXPORT DEF CRAM_OFFSET EQU 0x3F
EXPORT DEF CRAM_INCREMENT EQU 0x80

EXPORT DEF IO_CRAM_BKG_DATA EQU 0xFF69
EXPORT DEF IO_CRAM_OBJ_SELECT EQU 0xFF6A
EXPORT DEF IO_CRAM_OBJ_DATA EQU 0xFF6B

;misc io
EXPORT DEF IO_SPRITE_PRIORITY EQU 0xFF6C
EXPORT DEF IO_WRAM_BANK EQU 0xFF70
EXPORT DEF IO_UNK1 EQU 0xFF72
EXPORT DEF IO_UNK2 EQU 0xFF73
EXPORT DEF IO_UNK3 EQU 0xFF74
EXPORT DEF IO_UNK4 EQU 0xFF75
EXPORT DEF IO_PCM_12 EQU 0xFF76
EXPORT DEF IO_PCM_34 EQU 0xFF77
